version: '3.9'

services:
  # MongoDB container (no auth)
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d # optional initialization scripts

  # Mongo Express (web GUI)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_BASICAUTH_USERNAME: '' # no auth
      ME_CONFIG_BASICAUTH_PASSWORD: '' # no auth
    depends_on:
      - mongodb

  # NestJS app
  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/mydatabase' # database name here
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - mongo-express

volumes:
  mongo-data:
